'use client';

import { useState } from 'react';
import { AppShell } from '@/components/layout/AppShell';
import { Button, Badge, Avatar, PageHeader } from '@/components/ui';
import { mockAuditEvents } from '@/mock-data/audit';
import { formatDateTime } from '@/lib/utils';
import { FileText, User, ChevronRight, X, ExternalLink } from 'lucide-react';
import { AuditEvent } from '@/types';
import Link from 'next/link';

export default function AuditPage() {
  const [sourceFilter, setSourceFilter] = useState('all');
  const [selectedEvent, setSelectedEvent] = useState<AuditEvent | null>(null);

  const sorted = [...mockAuditEvents].sort((a, b) =>
    new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  );

  const filtered = sourceFilter === 'all' ? sorted : sorted.filter(e => e.source === sourceFilter);

  const sourceColors: Record<string, { color: string; bg: string }> = {
    resume: { color: '#065f46', bg: '#f0fdf4' },
    interview: { color: 'var(--accent)', bg: 'var(--accent-light)' },
    manual: { color: '#92400e', bg: '#fffbeb' },
    system: { color: '#6b7280', bg: '#f9fafb' },
    portfolio: { color: '#7c2d12', bg: '#fff7ed' },
    application: { color: '#1d4ed8', bg: '#eff6ff' },
  };

  return (
    <AppShell title="Audit Trail" breadcrumbs={[{ label: 'Audit Trail' }]}>
      <div>
        <PageHeader
          title="Audit Trail"
          subtitle="Traceable record of all analysis, evidence extraction, and actions."
        />

        {/* Filters */}
        <div style={{
          background: 'var(--bg-surface)',
          borderBottom: '1px solid var(--border-default)',
          padding: '12px 24px',
          display: 'flex',
          gap: 10,
          alignItems: 'center',
        }}>
          <select
            value={sourceFilter}
            onChange={e => setSourceFilter(e.target.value)}
            aria-label="Filter by source"
            style={{ padding: '7px 28px 7px 10px', border: '1px solid var(--border-default)', borderRadius: 7, fontSize: '0.8125rem', background: 'var(--bg-surface)', color: 'var(--text-primary)', cursor: 'pointer', outline: 'none' }}
          >
            <option value="all">All sources</option>
            <option value="resume">Resume</option>
            <option value="interview">Interview</option>
            <option value="manual">Manual</option>
            <option value="system">System</option>
          </select>
          <span style={{ fontSize: '0.8125rem', color: 'var(--text-muted)', marginLeft: 'auto' }}>
            {filtered.length} events
          </span>
        </div>

        <div style={{ display: 'flex', height: 'calc(100vh - 160px)', overflow: 'hidden' }}>
          {/* Audit table */}
          <div style={{ flex: 1, overflow: 'auto', padding: '16px 24px 48px' }}>
            <div style={{
              background: 'var(--bg-surface)',
              border: '1px solid var(--border-default)',
              borderRadius: 10,
              overflow: 'hidden',
            }}>
              <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                <thead>
                  <tr style={{ background: 'var(--bg-base)' }}>
                    {['Timestamp', 'Candidate', 'Insight', 'Source', 'Generated by', 'Action', ''].map(h => (
                      <th key={h} style={{
                        padding: '9px 14px', textAlign: 'left', fontSize: '0.6875rem',
                        fontWeight: 600, color: 'var(--text-muted)', letterSpacing: '0.04em',
                        textTransform: 'uppercase', borderBottom: '1px solid var(--border-default)',
                      }}>
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {filtered.map((event, i) => {
                    const { color, bg } = sourceColors[event.source] ?? { color: 'var(--text-muted)', bg: 'var(--bg-muted)' };
                    const isSelected = selectedEvent?.id === event.id;
                    return (
                      <tr
                        key={event.id}
                        onClick={() => setSelectedEvent(isSelected ? null : event)}
                        style={{
                          borderBottom: i < filtered.length - 1 ? '1px solid var(--border-muted)' : 'none',
                          cursor: 'pointer',
                          background: isSelected ? 'var(--accent-light)' : 'transparent',
                          borderLeft: isSelected ? '3px solid var(--accent)' : '3px solid transparent',
                        }}
                        onMouseEnter={e => { if (!isSelected) (e.currentTarget as HTMLElement).style.background = 'var(--bg-base)'; }}
                        onMouseLeave={e => { if (!isSelected) (e.currentTarget as HTMLElement).style.background = 'transparent'; }}
                      >
                        <td style={{ padding: '12px 14px', whiteSpace: 'nowrap' }}>
                          <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontFamily: 'monospace' }}>
                            {formatDateTime(event.timestamp)}
                          </span>
                        </td>
                        <td style={{ padding: '12px 14px' }}>
                          <Link
                            href={`/candidates/${event.candidateId}`}
                            onClick={e => e.stopPropagation()}
                            style={{ fontWeight: 600, fontSize: '0.8125rem', color: 'var(--accent)', textDecoration: 'none' }}
                          >
                            {event.candidateName}
                          </Link>
                          {event.jobTitle && (
                            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: 1 }}>{event.jobTitle}</div>
                          )}
                        </td>
                        <td style={{ padding: '12px 14px', maxWidth: 280 }}>
                          <div style={{ fontSize: '0.8125rem', color: 'var(--text-primary)', lineHeight: 1.5, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            {event.insight}
                          </div>
                        </td>
                        <td style={{ padding: '12px 14px' }}>
                          <Badge color={color} bg={bg}>{event.source}</Badge>
                        </td>
                        <td style={{ padding: '12px 14px', fontSize: '0.8125rem', color: 'var(--text-secondary)' }}>
                          {event.generatedBy === 'hireflow' ? (
                            <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                              <FileText size={12} color="var(--text-faint)" /> HireFlow
                            </span>
                          ) : (
                            <span style={{ display: 'flex', alignItems: 'center', gap: 4 }}>
                              <User size={12} color="var(--text-faint)" /> {event.generatedByUser ?? 'Recruiter'}
                            </span>
                          )}
                        </td>
                        <td style={{ padding: '12px 14px', fontSize: '0.8125rem', color: 'var(--text-muted)' }}>
                          {event.action}
                        </td>
                        <td style={{ padding: '12px 14px' }}>
                          {event.evidenceTrace && (
                            <Button variant="ghost" size="sm" onClick={e => { e.stopPropagation(); setSelectedEvent(event); }}>
                              Trace <ChevronRight size={13} />
                            </Button>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>

          {/* Evidence Trace Panel */}
          {selectedEvent && selectedEvent.evidenceTrace && (
            <div style={{
              width: 380,
              borderLeft: '1px solid var(--border-default)',
              background: 'var(--bg-surface)',
              overflow: 'auto',
              padding: 24,
              animation: 'slideIn 0.2s ease-out',
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 }}>
                <h2 style={{ margin: 0, fontSize: '1rem', fontWeight: 700, color: 'var(--text-primary)' }}>
                  Evidence Trace
                </h2>
                <button
                  onClick={() => setSelectedEvent(null)}
                  aria-label="Close evidence trace"
                  style={{ border: 'none', background: 'transparent', cursor: 'pointer', color: 'var(--text-muted)', display: 'flex' }}
                >
                  <X size={16} />
                </button>
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
                {/* Insight */}
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                    Insight
                  </div>
                  <p style={{ margin: 0, fontSize: '0.875rem', color: 'var(--text-primary)', lineHeight: 1.6, fontWeight: 500 }}>
                    &ldquo;{selectedEvent.evidenceTrace.insight}&rdquo;
                  </p>
                </div>

                {/* Source */}
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                    Source Document
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: '0.875rem', color: 'var(--text-primary)' }}>
                    <FileText size={14} color="var(--text-muted)" />
                    {selectedEvent.evidenceTrace.sourceDocument}
                  </div>
                </div>

                {/* Location */}
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                    Location
                  </div>
                  <div style={{ fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
                    {selectedEvent.evidenceTrace.location}
                  </div>
                </div>

                {/* Extracted evidence */}
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                    Extracted Evidence
                  </div>
                  <blockquote style={{
                    margin: 0,
                    padding: '10px 14px',
                    background: 'var(--bg-base)',
                    borderLeft: '3px solid var(--accent)',
                    borderRadius: '0 6px 6px 0',
                    fontSize: '0.8125rem',
                    color: 'var(--text-primary)',
                    lineHeight: 1.65,
                    fontStyle: 'italic',
                  }}>
                    &ldquo;{selectedEvent.evidenceTrace.extractedEvidence}&rdquo;
                  </blockquote>
                </div>

                {/* Reasoning */}
                <div>
                  <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                    Reasoning Context
                  </div>
                  <p style={{ margin: 0, fontSize: '0.8125rem', color: 'var(--text-secondary)', lineHeight: 1.7 }}>
                    {selectedEvent.evidenceTrace.reasoningContext}
                  </p>
                </div>

                {selectedEvent.evidenceTrace.requirementLabel && (
                  <div>
                    <div style={{ fontSize: '0.6875rem', fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 6 }}>
                      Requirement
                    </div>
                    <Badge>{selectedEvent.evidenceTrace.requirementLabel}</Badge>
                  </div>
                )}

                <Link href={`/candidates/${selectedEvent.candidateId}`} style={{ textDecoration: 'none' }}>
                  <Button variant="secondary" size="sm">
                    Open Candidate Profile <ExternalLink size={13} />
                  </Button>
                </Link>
              </div>
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}
