import { AuditEvent } from '@/types';

export const mockAuditEvents: AuditEvent[] = [
  {
    id: 'audit-001',
    timestamp: '2026-09-15T11:42:00Z',
    candidateId: 'cand-001',
    candidateName: 'Aarav Mehta',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Next.js experience validated via interview — candidate described ISR implementation and routing differences from CRA.',
    source: 'interview',
    sourceLabel: 'Interview Notes — 15 Sep 2026',
    generatedBy: 'hireflow',
    action: 'Requirement updated to Verified',
    evidenceTrace: {
      insight: 'Next.js experience validated via interview.',
      sourceDocument: 'Interview Notes — Alex Rivera, Jordan Kim — 15 Sep 2026',
      location: 'Technical questions section — Q4 follow-up',
      extractedEvidence: 'Candidate described migrating CRA app to Next.js. Used ISR for product pages, static export for marketing. Encountered webpack configuration differences and described resolution approach.',
      reasoningContext: 'Resume described the migration at a high level. Interview confirmed candidate drove the migration, made ISR vs SSR decisions, and handled deployment differences. This constitutes strong direct evidence.',
      requirementId: 'req-fe-5',
      requirementLabel: 'Next.js',
    },
  },
  {
    id: 'audit-002',
    timestamp: '2026-09-15T10:05:00Z',
    candidateId: 'cand-001',
    candidateName: 'Aarav Mehta',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Resume processed. React and TypeScript requirements confirmed as strong evidence.',
    source: 'resume',
    sourceLabel: 'Aarav_Mehta_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Evidence extracted',
    evidenceTrace: {
      insight: 'React and TypeScript requirements confirmed as strong evidence.',
      sourceDocument: 'Aarav_Mehta_Resume.pdf',
      location: 'Experience section — Zenpay (2023–present)',
      extractedEvidence: 'Led development of React-based merchant dashboard serving 200K+ daily users. Entire codebase in TypeScript. Migrated legacy JS codebases.',
      reasoningContext: 'Both required skills appear as primary tools in the most recent role. Evidence is direct and specific.',
      requirementId: 'req-fe-1',
      requirementLabel: 'React',
    },
  },
  {
    id: 'audit-003',
    timestamp: '2026-09-10T14:22:00Z',
    candidateId: 'cand-005',
    candidateName: 'Lena Bauer',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Next.js experience requires validation. Resume mentions SSR data fetching but not explicitly Next.js.',
    source: 'resume',
    sourceLabel: 'Lena_Bauer_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Validation question recommended',
    evidenceTrace: {
      insight: 'Next.js experience requires validation.',
      sourceDocument: 'Lena_Bauer_Resume.pdf',
      location: 'Projects section',
      extractedEvidence: 'Candidate mentions "React with server-side data fetching" in projects section.',
      reasoningContext: 'Next.js is a specific framework requirement. SSR data fetching can be implemented without Next.js (e.g., via custom Express server, Remix, or other frameworks). Explicit mention of Next.js is absent. Validation is required before marking this requirement as covered.',
      requirementId: 'req-fe-5',
      requirementLabel: 'Next.js',
    },
  },
  {
    id: 'audit-004',
    timestamp: '2026-09-11T09:15:00Z',
    candidateId: 'cand-004',
    candidateName: 'Sophie Chen',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'TypeScript evidence is partial. Skills section lists TypeScript but all project examples use JavaScript.',
    source: 'resume',
    sourceLabel: 'Sophie_Chen_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Requirement flagged as Partial Evidence',
    evidenceTrace: {
      insight: 'TypeScript evidence is partial.',
      sourceDocument: 'Sophie_Chen_Resume.pdf',
      location: 'Skills section and Projects section',
      extractedEvidence: 'Skills: React, JavaScript, SCSS, Framer Motion, TypeScript (listed). Projects: All examples reference JavaScript and no explicit TypeScript usage described.',
      reasoningContext: 'TypeScript is listed in skills but there is no project or experience evidence showing TypeScript usage in a production context. A personal project mention does not constitute the same confidence level as production usage. This discrepancy should be explored in screening.',
      requirementId: 'req-fe-2',
      requirementLabel: 'TypeScript',
    },
  },
  {
    id: 'audit-005',
    timestamp: '2026-09-12T11:00:00Z',
    candidateId: 'cand-007',
    candidateName: 'Ingrid Larsson',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Frontend-specific experience tenure unclear. Candidate has 5 years total but significant backend and full-stack work.',
    source: 'resume',
    sourceLabel: 'Ingrid_Larsson_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Experience requirement flagged as Needs Validation',
    evidenceTrace: {
      insight: 'Frontend-specific experience tenure unclear.',
      sourceDocument: 'Ingrid_Larsson_Resume.pdf',
      location: 'Work History section',
      extractedEvidence: 'Klarna (2021–present): Full-Stack Developer. Prior role: Java Backend Engineer (2019–2021). React is mentioned as a technology used at Klarna.',
      reasoningContext: 'The role requires 3+ years frontend development experience. The candidate has 5 years total, but 2 of those were explicitly backend. The Klarna role is described as "Full-Stack" — the frontend portion is unclear and may represent a minority of the work. Frontend-specific tenure cannot be confirmed without further information.',
      requirementId: 'req-fe-3',
      requirementLabel: '3+ years frontend development',
    },
  },
  {
    id: 'audit-006',
    timestamp: '2026-09-15T14:30:00Z',
    candidateId: 'cand-001',
    candidateName: 'Aarav Mehta',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Interview completed. Leadership requirement partially covered — team lead scope confirmed but no formal people management role.',
    source: 'interview',
    sourceLabel: 'Interview Summary — 15 Sep 2026',
    generatedBy: 'hireflow',
    action: 'Requirement updated to Partial Evidence',
    evidenceTrace: {
      insight: 'Leadership requirement partially covered.',
      sourceDocument: 'Interview Notes — Alex Rivera, Jordan Kim — 15 Sep 2026',
      location: 'Leadership questions section',
      extractedEvidence: 'Candidate manages 4-person frontend team. Describes 1:1s, PR review rotation, architecture RFCs, and mentoring. Does not hold formal engineering manager title.',
      reasoningContext: 'The job description mentions team or tech leadership. The candidate demonstrates clear tech leadership behaviors but without a formal people management role (no performance review responsibility confirmed). The evidence covers tech lead scope but not full team management.',
      requirementId: 'req-fe-8',
      requirementLabel: 'Team/tech leadership',
    },
  },
  {
    id: 'audit-007',
    timestamp: '2026-09-16T09:00:00Z',
    candidateId: 'cand-002',
    candidateName: 'Marcos Oliveira',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Resume processed. Strong React and TypeScript evidence from Shopify role.',
    source: 'resume',
    sourceLabel: 'Marcos_Oliveira_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Evidence extracted',
    evidenceTrace: {
      insight: 'Strong React and TypeScript evidence from Shopify.',
      sourceDocument: 'Marcos_Oliveira_Resume.pdf',
      location: 'Experience — Shopify (2022–present)',
      extractedEvidence: 'Senior React engineer building merchant catalog editor. All Shopify frontend code in TypeScript with strict config.',
      reasoningContext: 'Shopify is a well-known large-scale React and TypeScript environment. Evidence is contextually credible and specific.',
      requirementId: 'req-fe-1',
      requirementLabel: 'React',
    },
  },
  {
    id: 'audit-008',
    timestamp: '2026-09-14T10:35:00Z',
    candidateId: 'cand-009',
    candidateName: 'Fatima Al-Hassan',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'TypeScript not evidenced anywhere in resume. This is a required skill.',
    source: 'resume',
    sourceLabel: 'Fatima_AlHassan_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Required requirement marked Not Found',
    evidenceTrace: {
      insight: 'TypeScript not evidenced in resume.',
      sourceDocument: 'Fatima_AlHassan_Resume.pdf',
      location: 'Skills section, Projects section, Experience section',
      extractedEvidence: 'Skills listed: React, HTML/CSS, JavaScript, Bootstrap. No TypeScript mentioned in any section.',
      reasoningContext: 'TypeScript is a required skill for this role. The candidate lists JavaScript but not TypeScript. This is a meaningful gap for a senior frontend position where TypeScript proficiency is expected.',
      requirementId: 'req-fe-2',
      requirementLabel: 'TypeScript',
    },
  },
  {
    id: 'audit-009',
    timestamp: '2026-09-17T16:00:00Z',
    candidateId: 'cand-003',
    candidateName: 'Priya Nair',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Interview completed. All requirements covered. Performance optimization evidence exceptional.',
    source: 'interview',
    sourceLabel: 'Interview Summary — 17 Sep 2026',
    generatedBy: 'hireflow',
    action: 'Evaluation ready',
  },
  {
    id: 'audit-010',
    timestamp: '2026-09-18T09:00:00Z',
    candidateId: 'cand-001',
    candidateName: 'Aarav Mehta',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Recruiter manually updated candidate stage from Interview to Evaluation.',
    source: 'manual',
    sourceLabel: 'Manual — Alex Rivera',
    generatedBy: 'recruiter',
    generatedByUser: 'Alex Rivera',
    action: 'Stage updated',
  },
  {
    id: 'audit-011',
    timestamp: '2026-09-19T08:30:00Z',
    candidateId: 'cand-006',
    candidateName: 'Kwame Asante',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Performance optimization claim in resume lacks specifics. Requires validation during screening.',
    source: 'resume',
    sourceLabel: 'Kwame_Asante_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Validation question recommended',
    evidenceTrace: {
      insight: 'Performance optimization claim requires validation.',
      sourceDocument: 'Kwame_Asante_Resume.pdf',
      location: 'Achievements section',
      extractedEvidence: '"Optimized payment flow performance at Flutterwave." No metrics, tools, or approach described.',
      reasoningContext: 'Performance optimization is a preferred requirement. The claim exists but is unsubstantiated — no metrics, no tooling mentioned, no before/after comparison. A screening question should establish what was actually done and what was measured.',
      requirementId: 'req-fe-6',
      requirementLabel: 'Performance optimization',
    },
  },
  {
    id: 'audit-012',
    timestamp: '2026-09-19T09:15:00Z',
    candidateId: 'cand-008',
    candidateName: 'Daniel Park',
    jobId: 'job-fe-001',
    jobTitle: 'Senior Frontend Engineer',
    insight: 'Primary framework may be Vue.js, not React. Current role at TikTok uses Vue primarily.',
    source: 'resume',
    sourceLabel: 'Daniel_Park_Resume.pdf',
    generatedBy: 'hireflow',
    action: 'Requirement flagged as Partial Evidence',
    evidenceTrace: {
      insight: 'Primary framework may be Vue.js, not React.',
      sourceDocument: 'Daniel_Park_Resume.pdf',
      location: 'Experience — TikTok and Skills section',
      extractedEvidence: 'Skills: "React, Vue.js, TypeScript". TikTok projects described use Nuxt.js (Vue framework). React mentioned in skills but no project example uses React.',
      reasoningContext: 'The candidate lists both React and Vue.js. Project examples use Nuxt, which is the Vue.js equivalent of Next.js. This suggests Vue.js is the primary framework and React may be secondary or aspirational. React proficiency should be verified explicitly.',
      requirementId: 'req-fe-1',
      requirementLabel: 'React',
    },
  },
];

export const getAuditEventsForCandidate = (candidateId: string): AuditEvent[] =>
  mockAuditEvents.filter(e => e.candidateId === candidateId);

export const getAuditEventsForJob = (jobId: string): AuditEvent[] =>
  mockAuditEvents.filter(e => e.jobId === jobId);
