import { Candidate, Evidence, CandidateSummary } from '@/types';

const avatarColors = [
  '#3730a3', '#0369a1', '#065f46', '#7c2d12', '#6b21a8',
  '#0f766e', '#9f1239', '#1d4ed8', '#b45309', '#4f46e5',
];

function makeEvidence(reqId: string, status: Evidence['status'], excerpt: string, source: Evidence['source'], location: string): Evidence {
  return {
    id: `ev-${reqId}-${Math.random().toString(36).slice(2, 7)}`,
    requirementId: reqId,
    status,
    excerpt,
    source,
    sourceLabel: source === 'resume' ? 'Resume' : source === 'interview' ? 'Interview Notes' : source === 'portfolio' ? 'Portfolio' : 'Application',
    location,
  };
}

const candidateSummaryAarav: CandidateSummary = {
  overview: 'Aarav is a senior frontend engineer with 6 years of experience building complex React applications at scale. He has contributed to design systems, led frontend architecture decisions, and has strong TypeScript expertise.',
  experience: '6 years in frontend engineering at two Series B startups. Currently tech lead at Zenpay, managing a 4-person frontend team. Previously built customer-facing dashboards at Razorpay.',
  skills: 'React, TypeScript, Next.js, Webpack, CSS-in-JS, Storybook, GraphQL, Jest, Playwright.',
  projects: 'Led migration of Zenpay merchant dashboard from CRA to Next.js (30% LCP improvement). Built shared component library adopted by 3 product teams.',
  education: 'B.Tech Computer Science, IIT Bombay, 2020.',
  domainExperience: 'Fintech, payments, merchant-facing tools, high-volume transactional UIs.',
  potentialGaps: 'Limited explicit mention of backend architecture exposure. Leadership experience is team-level but no cross-functional program management.',
};

const candidateSummarySophie: CandidateSummary = {
  overview: 'Sophie is a frontend engineer with 4 years of experience, primarily in consumer products. Strong React and CSS skills. TypeScript mentioned but limited production evidence in resume.',
  experience: '4 years at Headspace and previously a design agency. Built animation-heavy marketing pages and prototype UIs. Less exposure to large-scale product engineering.',
  skills: 'React, JavaScript, SCSS, Framer Motion, Figma-to-code, some TypeScript.',
  projects: 'Rebuilt Headspace onboarding flow (reduced drop-off by 18%). Led animation framework for marketing site.',
  education: 'B.Sc Interactive Media Design, Parsons School of Design, 2022.',
  domainExperience: 'Consumer wellness apps, marketing, animation-heavy UIs.',
  potentialGaps: 'TypeScript evidence limited to side projects. No evidence of design system ownership. No backend or API integration experience at scale.',
};

const candidateSummaryMarcos: CandidateSummary = {
  overview: 'Marcos is a full-stack engineer with deep React and Node.js experience. 5 years of professional experience with strong TypeScript usage. Recently shifted focus to frontend, but has full-stack background.',
  experience: '5 years across frontend and backend. Currently senior engineer at Shopify, building merchant tooling with React and TypeScript.',
  skills: 'React, TypeScript, Node.js, GraphQL, PostgreSQL, Next.js, Remix, testing.',
  projects: 'Rebuilt Shopify product catalog editor in React + TypeScript. Contributed to internal component library. Wrote performance profiling guide adopted by the team.',
  education: 'B.Sc Software Engineering, University of Waterloo, 2021.',
  domainExperience: 'E-commerce, merchant tools, developer tooling.',
  potentialGaps: 'Leadership experience is informal — no direct reports or formal tech lead title. Some frontend focus may be more recent.',
};

export const mockCandidates: Candidate[] = [
  // ─── Strong Match ──────────────────────────────────────────────
  {
    id: 'cand-001',
    jobId: 'job-fe-001',
    name: 'Aarav Mehta',
    firstName: 'Aarav',
    lastName: 'Mehta',
    email: 'aarav.mehta@email.com',
    currentRole: 'Frontend Tech Lead',
    currentCompany: 'Zenpay',
    location: 'Mumbai, India (Remote)',
    yearsExperience: 6,
    skills: ['React', 'TypeScript', 'Next.js', 'Webpack', 'Storybook', 'GraphQL'],
    education: 'B.Tech CS, IIT Bombay',
    stage: 'interview',
    group: 'strong_match',
    requirementCoverage: 94,
    validationNeeded: false,
    interviewStatus: 'completed',
    documents: [
      { id: 'doc-001', name: 'Aarav_Mehta_Resume.pdf', type: 'resume', uploadedAt: '2026-08-28T10:00:00Z', status: 'ready', size: '145 KB' },
      { id: 'doc-002', name: 'Portfolio', type: 'portfolio', uploadedAt: '2026-08-28T10:05:00Z', status: 'ready' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'verified', 'Led development of React-based merchant dashboard serving 200K+ daily users. Migrated core application from CRA to Next.js.', 'resume', 'Experience — Zenpay (2023–present)'),
      makeEvidence('req-fe-2', 'verified', 'Entire Zenpay codebase is TypeScript. Wrote internal TypeScript style guide. Migrated legacy JS codebases.', 'resume', 'Experience — Zenpay'),
      makeEvidence('req-fe-3', 'verified', 'Frontend Tech Lead at Zenpay (2023–present), Senior Frontend at Razorpay (2020–2023). Total 6 years professional frontend.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'strong', 'Built shared component library adopted by 3 product teams. Documented design tokens and accessibility standards.', 'resume', 'Projects section'),
      makeEvidence('req-fe-5', 'verified', 'Migrated merchant dashboard to Next.js. Implemented ISR and edge caching. 30% LCP improvement post-migration.', 'resume', 'Experience — Zenpay'),
      makeEvidence('req-fe-6', 'strong', 'Led Core Web Vitals initiative. Reduced LCP by 30%, eliminated layout shift on checkout flow.', 'interview', 'Interview — technical round'),
      makeEvidence('req-fe-7', 'strong', 'Built Zenpay Design System (Figma + Storybook + npm package). Used by 3 teams.', 'resume', 'Projects section'),
      makeEvidence('req-fe-8', 'partial', 'Manages 4-person frontend team. Described mentoring and code review culture. No formal engineering manager title.', 'interview', 'Interview — leadership questions'),
    ],
    summary: candidateSummaryAarav,
    addedAt: '2026-08-28T10:00:00Z',
    updatedAt: '2026-09-15T14:30:00Z',
    initials: 'AM',
    avatarColor: avatarColors[0],
  },
  {
    id: 'cand-002',
    jobId: 'job-fe-001',
    name: 'Marcos Oliveira',
    firstName: 'Marcos',
    lastName: 'Oliveira',
    email: 'marcos.oliveira@email.com',
    currentRole: 'Senior Software Engineer',
    currentCompany: 'Shopify',
    location: 'Toronto, Canada (Remote)',
    yearsExperience: 5,
    skills: ['React', 'TypeScript', 'Next.js', 'GraphQL', 'Node.js', 'Testing'],
    education: 'B.Sc Software Engineering, University of Waterloo',
    stage: 'evaluation',
    group: 'strong_match',
    requirementCoverage: 88,
    validationNeeded: false,
    interviewStatus: 'completed',
    documents: [
      { id: 'doc-003', name: 'Marcos_Oliveira_Resume.pdf', type: 'resume', uploadedAt: '2026-09-01T09:00:00Z', status: 'ready', size: '132 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'verified', 'Senior React engineer at Shopify. Built merchant catalog editor using React with complex state management.', 'resume', 'Experience — Shopify (2022–present)'),
      makeEvidence('req-fe-2', 'verified', 'All Shopify projects in TypeScript. Mentioned strict TypeScript config and type-safe API layer.', 'resume', 'Skills section'),
      makeEvidence('req-fe-3', 'verified', '5 years professional experience. 3 years senior-level.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'strong', 'Contributed to Shopify Polaris component library. Wrote performance profiling guide.', 'resume', 'Projects section'),
      makeEvidence('req-fe-5', 'strong', 'Used Next.js and Remix for internal tooling projects. SSR-first architecture.', 'resume', 'Projects section'),
      makeEvidence('req-fe-6', 'strong', 'Reduced bundle size by 40% through code splitting. Authored internal perf guide.', 'resume', 'Achievements'),
      makeEvidence('req-fe-7', 'partial', 'Contributed to Polaris but did not own the library.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'needs_validation', 'Mentioned mentoring but no formal lead title. Interview should clarify scope.', 'resume', 'Experience'),
    ],
    summary: candidateSummaryMarcos,
    addedAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-16T11:00:00Z',
    initials: 'MO',
    avatarColor: avatarColors[1],
  },
  {
    id: 'cand-003',
    jobId: 'job-fe-001',
    name: 'Priya Nair',
    firstName: 'Priya',
    lastName: 'Nair',
    email: 'priya.nair@email.com',
    currentRole: 'Staff Frontend Engineer',
    currentCompany: 'Figma',
    location: 'San Francisco, CA',
    yearsExperience: 8,
    skills: ['React', 'TypeScript', 'WebGL', 'Performance', 'Design Systems'],
    education: 'M.S. Computer Science, Stanford University',
    stage: 'evaluation',
    group: 'strong_match',
    requirementCoverage: 97,
    validationNeeded: false,
    interviewStatus: 'completed',
    documents: [
      { id: 'doc-004', name: 'Priya_Nair_Resume.pdf', type: 'resume', uploadedAt: '2026-08-25T11:00:00Z', status: 'ready', size: '189 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'verified', 'Staff engineer at Figma working on collaborative editing frontend. React architecture expert.', 'resume', 'Experience — Figma'),
      makeEvidence('req-fe-2', 'verified', 'Deep TypeScript experience. Presented at TypeScript Congress 2025.', 'resume', 'Speaking & Publications'),
      makeEvidence('req-fe-3', 'verified', '8 years frontend engineering. 3 years as staff engineer.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'verified', 'Owns Figma\'s component token system. Led design system v3 migration.', 'resume', 'Leadership section'),
      makeEvidence('req-fe-5', 'verified', 'Extensive Next.js production usage across 3 projects.', 'resume', 'Projects'),
      makeEvidence('req-fe-6', 'verified', 'Core Web Vitals optimization expert. Reduced Figma editor load time by 45%.', 'interview', 'Technical interview'),
      makeEvidence('req-fe-7', 'verified', 'Figma design system owner for 2 years. Component library used globally.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'verified', 'Staff engineer managing 6-person frontend platform team.', 'resume', 'Leadership'),
    ],
    summary: {
      overview: 'Priya is a Staff Frontend Engineer at Figma with 8 years of experience. Exceptional coverage of all core requirements.',
      experience: '8 years. Staff Engineer at Figma (3 years), Senior at Stripe (3 years), engineer at Airbnb (2 years).',
      skills: 'React, TypeScript, WebGL, CSS, Design Systems, Performance, WebAssembly.',
      projects: 'Collaborative editing engine frontend. Figma Design System v3. Plugin sandbox architecture.',
      education: 'M.S. Computer Science, Stanford University.',
      domainExperience: 'Design tooling, collaborative software, high-performance browser applications.',
      potentialGaps: 'Overqualified for some aspects of the role. May need role scope discussion.',
    },
    addedAt: '2026-08-25T11:00:00Z',
    updatedAt: '2026-09-17T15:00:00Z',
    initials: 'PN',
    avatarColor: avatarColors[2],
  },
  // ─── Potential Match ──────────────────────────────────────────────
  {
    id: 'cand-004',
    jobId: 'job-fe-001',
    name: 'Sophie Chen',
    firstName: 'Sophie',
    lastName: 'Chen',
    email: 'sophie.chen@email.com',
    currentRole: 'Frontend Engineer',
    currentCompany: 'Headspace',
    location: 'Los Angeles, CA',
    yearsExperience: 4,
    skills: ['React', 'JavaScript', 'SCSS', 'Framer Motion', 'Figma'],
    education: 'B.Sc Interactive Media, Parsons',
    stage: 'screening',
    group: 'potential_match',
    requirementCoverage: 62,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-005', name: 'Sophie_Chen_Resume.pdf', type: 'resume', uploadedAt: '2026-09-05T14:00:00Z', status: 'ready', size: '110 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'strong', 'Built React-based UI components for Headspace iOS web wrapper. Uses React hooks and context API.', 'resume', 'Experience — Headspace'),
      makeEvidence('req-fe-2', 'partial', 'Resume mentions TypeScript in skills but project examples are in JavaScript. One personal project uses TypeScript.', 'resume', 'Skills section'),
      makeEvidence('req-fe-3', 'partial', '4 years total experience but 2 years at an agency on marketing sites, not product engineering.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'partial', 'Built reusable animation components. No dedicated design system ownership mentioned.', 'resume', 'Projects'),
      makeEvidence('req-fe-5', 'not_found', 'No mention of Next.js in resume or portfolio.', 'resume', 'Skills section'),
      makeEvidence('req-fe-6', 'not_found', 'No performance optimization experience mentioned.', 'resume', 'Experience'),
      makeEvidence('req-fe-7', 'not_found', 'No design system ownership. CSS component library work is minor.', 'resume', 'Projects'),
      makeEvidence('req-fe-8', 'not_found', 'Individual contributor, no leadership evidence.', 'resume', 'Experience'),
    ],
    summary: candidateSummarySophie,
    addedAt: '2026-09-05T14:00:00Z',
    updatedAt: '2026-09-10T09:00:00Z',
    initials: 'SC',
    avatarColor: avatarColors[3],
  },
  {
    id: 'cand-005',
    jobId: 'job-fe-001',
    name: 'Lena Bauer',
    firstName: 'Lena',
    lastName: 'Bauer',
    email: 'lena.bauer@email.com',
    currentRole: 'Frontend Developer',
    currentCompany: 'N26',
    location: 'Berlin, Germany (Remote)',
    yearsExperience: 5,
    skills: ['React', 'TypeScript', 'CSS Modules', 'Storybook', 'Jest'],
    education: 'B.Sc Media Informatics, TU Berlin',
    stage: 'interview',
    group: 'potential_match',
    requirementCoverage: 74,
    validationNeeded: true,
    interviewStatus: 'scheduled',
    documents: [
      { id: 'doc-006', name: 'Lena_Bauer_Resume.pdf', type: 'resume', uploadedAt: '2026-09-03T08:00:00Z', status: 'ready', size: '128 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'verified', 'React developer at N26 fintech for 3 years. Builds account management and transaction UIs.', 'resume', 'Experience — N26'),
      makeEvidence('req-fe-2', 'strong', 'All N26 frontend code is TypeScript. Describes strict mode usage.', 'resume', 'Experience — N26'),
      makeEvidence('req-fe-3', 'strong', '5 years frontend. 3 years in fintech product.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'partial', 'Uses Storybook for component documentation but no design system ownership.', 'resume', 'Skills'),
      makeEvidence('req-fe-5', 'needs_validation', 'Mentions SSR interest and "React with server-side data fetching" but not explicitly Next.js.', 'resume', 'Projects'),
      makeEvidence('req-fe-6', 'needs_validation', 'Performance mentioned in context of form validation optimization. Unclear if this extends to broader web vitals work.', 'resume', 'Achievements'),
      makeEvidence('req-fe-7', 'not_found', 'Component library user but no ownership.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'Individual contributor. No leadership evidence.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Lena is a solid React and TypeScript developer with fintech experience. Strong fundamentals but gaps in leadership and design system ownership.',
      experience: '5 years. N26 (fintech, 3 years), web agency (2 years).',
      skills: 'React, TypeScript, CSS Modules, Storybook, Jest, Cypress.',
      projects: 'Account management UI at N26. Transaction filtering component library. Automated visual regression testing setup.',
      education: 'B.Sc Media Informatics, TU Berlin.',
      domainExperience: 'Fintech, consumer banking, regulatory-driven UIs.',
      potentialGaps: 'No Next.js confirmation. No design system ownership. No leadership experience mentioned.',
    },
    addedAt: '2026-09-03T08:00:00Z',
    updatedAt: '2026-09-12T10:30:00Z',
    initials: 'LB',
    avatarColor: avatarColors[4],
  },
  {
    id: 'cand-006',
    jobId: 'job-fe-001',
    name: 'Kwame Asante',
    firstName: 'Kwame',
    lastName: 'Asante',
    email: 'kwame.asante@email.com',
    currentRole: 'React Developer',
    currentCompany: 'Flutterwave',
    location: 'Lagos, Nigeria (Remote)',
    yearsExperience: 4,
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Firebase'],
    education: 'B.Sc Computer Science, University of Ghana',
    stage: 'screening',
    group: 'potential_match',
    requirementCoverage: 68,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-007', name: 'Kwame_Asante_Resume.pdf', type: 'resume', uploadedAt: '2026-09-08T12:00:00Z', status: 'ready', size: '98 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'verified', 'React developer at Flutterwave building payment checkout UIs.', 'resume', 'Experience — Flutterwave'),
      makeEvidence('req-fe-2', 'strong', 'TypeScript throughout all project descriptions. Strict TypeScript mentioned.', 'resume', 'Projects'),
      makeEvidence('req-fe-3', 'partial', '4 years total but includes 1 year of freelance. Product experience is 3 years.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'partial', 'Uses Tailwind. No design system or component library ownership.', 'resume', 'Skills'),
      makeEvidence('req-fe-5', 'not_found', 'No Next.js mentioned.', 'resume', 'Skills'),
      makeEvidence('req-fe-6', 'needs_validation', 'Mentions "optimized payment flow performance" but no specifics or metrics.', 'resume', 'Achievements'),
      makeEvidence('req-fe-7', 'not_found', 'No design system work.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'No leadership experience.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Kwame is a React and TypeScript developer with 4 years of experience in fintech. Solid core skills but limited depth in some required areas.',
      experience: '4 years. Flutterwave (3 years), freelance (1 year).',
      skills: 'React, TypeScript, Tailwind, Firebase, REST APIs.',
      projects: 'Payment checkout flow at Flutterwave. Open-source React component contribution.',
      education: 'B.Sc Computer Science, University of Ghana.',
      domainExperience: 'Fintech, payment UIs, African market products.',
      potentialGaps: 'No Next.js. No design system ownership. No performance work with metrics. Leadership not evidenced.',
    },
    addedAt: '2026-09-08T12:00:00Z',
    updatedAt: '2026-09-12T08:00:00Z',
    initials: 'KA',
    avatarColor: avatarColors[5],
  },
  // ─── Needs Validation ──────────────────────────────────────────────
  {
    id: 'cand-007',
    jobId: 'job-fe-001',
    name: 'Ingrid Larsson',
    firstName: 'Ingrid',
    lastName: 'Larsson',
    email: 'ingrid.larsson@email.com',
    currentRole: 'Full-Stack Developer',
    currentCompany: 'Klarna',
    location: 'Stockholm, Sweden (Remote)',
    yearsExperience: 5,
    skills: ['React', 'Java', 'TypeScript', 'Spring Boot', 'Kafka'],
    education: 'B.Sc IT, KTH Royal Institute of Technology',
    stage: 'screening',
    group: 'needs_validation',
    requirementCoverage: 55,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-008', name: 'Ingrid_Larsson_Resume.pdf', type: 'resume', uploadedAt: '2026-09-10T09:00:00Z', status: 'ready', size: '155 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'partial', 'Uses React on the frontend portion of full-stack role. Unclear depth of frontend ownership.', 'resume', 'Experience — Klarna'),
      makeEvidence('req-fe-2', 'needs_validation', 'TypeScript listed in skills but most project examples appear to use Java/Spring. Frontend TS use unclear.', 'resume', 'Skills section'),
      makeEvidence('req-fe-3', 'needs_validation', '5 years total but significant time in backend and full-stack roles. Frontend-specific tenure unclear.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'not_found', 'No mention of CSS ownership, design systems, or component libraries.', 'resume', 'Experience'),
      makeEvidence('req-fe-5', 'not_found', 'No Next.js mentioned. Uses Spring Boot for server-side.', 'resume', 'Skills'),
      makeEvidence('req-fe-6', 'not_found', 'No frontend performance work evident.', 'resume', 'Experience'),
      makeEvidence('req-fe-7', 'not_found', 'No design system work.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'Individual contributor.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Ingrid is a full-stack developer with strong backend skills but unclear frontend depth. Validation needed on TypeScript and React proficiency.',
      experience: '5 years full-stack. Frontend specifics unclear from resume alone.',
      skills: 'React, TypeScript (frontend?), Java, Spring Boot, Kafka, PostgreSQL.',
      projects: 'Klarna buy-now-pay-later flow (full-stack). Kafka event streaming pipeline.',
      education: 'B.Sc IT, KTH Royal Institute of Technology.',
      domainExperience: 'Fintech, BNPL, distributed systems.',
      potentialGaps: 'Frontend-specific experience needs validation. No design system, performance, or leadership evidence.',
    },
    addedAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
    initials: 'IL',
    avatarColor: avatarColors[6],
  },
  {
    id: 'cand-008',
    jobId: 'job-fe-001',
    name: 'Daniel Park',
    firstName: 'Daniel',
    lastName: 'Park',
    email: 'daniel.park@email.com',
    currentRole: 'Frontend Engineer',
    currentCompany: 'TikTok',
    location: 'Seoul, South Korea (Remote)',
    yearsExperience: 3,
    skills: ['React', 'Vue.js', 'TypeScript', 'Node.js', 'GraphQL'],
    education: 'B.Sc Computer Science, KAIST',
    stage: 'screening',
    group: 'needs_validation',
    requirementCoverage: 58,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-009', name: 'Daniel_Park_Resume.pdf', type: 'resume', uploadedAt: '2026-09-11T07:00:00Z', status: 'ready', size: '102 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'partial', 'React mentioned alongside Vue.js. Unclear which is primary. Current role appears to use Vue primarily.', 'resume', 'Skills — TikTok'),
      makeEvidence('req-fe-2', 'strong', 'TypeScript throughout all project descriptions. Strict mode.', 'resume', 'Projects'),
      makeEvidence('req-fe-3', 'partial', '3 years experience — meets minimum but on the lower end for senior role.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'partial', 'Some CSS work. No design system mentioned.', 'resume', 'Skills'),
      makeEvidence('req-fe-5', 'not_found', 'No Next.js. Uses Nuxt (Vue equivalent).', 'resume', 'Projects'),
      makeEvidence('req-fe-6', 'needs_validation', 'Mentions optimization but context is unclear.', 'resume', 'Achievements'),
      makeEvidence('req-fe-7', 'not_found', 'No design system ownership.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'No leadership experience.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Daniel has strong TypeScript skills but primary framework appears to be Vue.js, not React. React proficiency and seniority need validation.',
      experience: '3 years. TikTok frontend team.',
      skills: 'React, Vue.js (primary?), TypeScript, GraphQL, Node.js.',
      projects: 'TikTok creator analytics dashboard. Internal tooling in Vue.',
      education: 'B.Sc Computer Science, KAIST.',
      domainExperience: 'Social media, content platforms, analytics UIs.',
      potentialGaps: 'React vs Vue primary framework unclear. 3 years may be below desired seniority. No Next.js, design system, or leadership.',
    },
    addedAt: '2026-09-11T07:00:00Z',
    updatedAt: '2026-09-14T08:00:00Z',
    initials: 'DP',
    avatarColor: avatarColors[7],
  },
  // ─── Insufficient Evidence ──────────────────────────────────────────────
  {
    id: 'cand-009',
    jobId: 'job-fe-001',
    name: 'Fatima Al-Hassan',
    firstName: 'Fatima',
    lastName: 'Al-Hassan',
    email: 'fatima.alhassan@email.com',
    currentRole: 'Software Developer',
    currentCompany: 'Talent Plus',
    location: 'Riyadh, Saudi Arabia',
    yearsExperience: 3,
    skills: ['React', 'HTML/CSS', 'JavaScript', 'Bootstrap'],
    education: 'B.Sc Information Systems, King Saud University',
    stage: 'applied',
    group: 'insufficient_evidence',
    requirementCoverage: 30,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-010', name: 'Fatima_AlHassan_Resume.pdf', type: 'resume', uploadedAt: '2026-09-14T10:00:00Z', status: 'needs_review', size: '78 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'partial', 'React mentioned in skills list. No React-specific project examples provided.', 'resume', 'Skills section'),
      makeEvidence('req-fe-2', 'not_found', 'No TypeScript mentioned anywhere in resume.', 'resume', 'Skills section'),
      makeEvidence('req-fe-3', 'partial', '3 years as "Software Developer" with unclear frontend/backend split.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'not_found', 'Bootstrap used. No custom CSS or design system work.', 'resume', 'Skills'),
      makeEvidence('req-fe-5', 'not_found', 'No Next.js.', 'resume', 'Skills'),
      makeEvidence('req-fe-6', 'not_found', 'No performance work.', 'resume', 'Experience'),
      makeEvidence('req-fe-7', 'not_found', 'No design system work.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'No leadership.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Limited evidence available. React is listed as a skill but no project examples demonstrate production React experience. TypeScript not evidenced.',
      experience: '3 years as Software Developer. Frontend scope unclear.',
      skills: 'React (listed), HTML/CSS, JavaScript, Bootstrap.',
      projects: 'No specific project details in resume.',
      education: 'B.Sc Information Systems, King Saud University.',
      domainExperience: 'Unknown based on available information.',
      potentialGaps: 'TypeScript evidence completely absent. No Next.js, design systems, performance, or leadership. React depth unverified.',
    },
    addedAt: '2026-09-14T10:00:00Z',
    updatedAt: '2026-09-14T10:30:00Z',
    initials: 'FA',
    avatarColor: avatarColors[8],
  },
  {
    id: 'cand-010',
    jobId: 'job-fe-001',
    name: 'Riya Kapoor',
    firstName: 'Riya',
    lastName: 'Kapoor',
    email: 'riya.kapoor@email.com',
    currentRole: 'UI Developer',
    currentCompany: 'InfoSys',
    location: 'Bengaluru, India',
    yearsExperience: 2,
    skills: ['Angular', 'HTML', 'CSS', 'JavaScript'],
    education: 'B.E. Computer Science, VTU',
    stage: 'applied',
    group: 'insufficient_evidence',
    requirementCoverage: 18,
    validationNeeded: true,
    interviewStatus: undefined,
    documents: [
      { id: 'doc-011', name: 'Riya_Kapoor_Resume.pdf', type: 'resume', uploadedAt: '2026-09-15T11:00:00Z', status: 'ready', size: '92 KB' },
    ],
    evidence: [
      makeEvidence('req-fe-1', 'not_found', 'Primary framework is Angular. No React mentioned.', 'resume', 'Skills section'),
      makeEvidence('req-fe-2', 'not_found', 'No TypeScript mentioned. JavaScript only.', 'resume', 'Skills'),
      makeEvidence('req-fe-3', 'not_found', '2 years experience — below required 3+ years.', 'resume', 'Work history'),
      makeEvidence('req-fe-4', 'not_found', 'No design system work.', 'resume', 'Experience'),
      makeEvidence('req-fe-5', 'not_found', 'No Next.js.', 'resume', 'Skills'),
      makeEvidence('req-fe-6', 'not_found', 'No performance work.', 'resume', 'Experience'),
      makeEvidence('req-fe-7', 'not_found', 'No design system.', 'resume', 'Experience'),
      makeEvidence('req-fe-8', 'not_found', 'No leadership.', 'resume', 'Experience'),
    ],
    summary: {
      overview: 'Currently works with Angular, not React. Below minimum experience threshold for the role. Missing most core requirements.',
      experience: '2 years. InfoSys UI developer. Primarily Angular.',
      skills: 'Angular, HTML, CSS, JavaScript.',
      projects: 'Internal admin UI projects at InfoSys.',
      education: 'B.E. Computer Science, VTU.',
      domainExperience: 'IT services, admin tools.',
      potentialGaps: 'Wrong primary framework. Below experience minimum. TypeScript not evidenced. All preferred requirements missing.',
    },
    addedAt: '2026-09-15T11:00:00Z',
    updatedAt: '2026-09-15T11:30:00Z',
    initials: 'RK',
    avatarColor: avatarColors[9],
  },
];

export const getCandidatesForJob = (jobId: string): Candidate[] =>
  mockCandidates.filter(c => c.jobId === jobId);

export const getCandidateById = (id: string): Candidate | undefined =>
  mockCandidates.find(c => c.id === id);
