import { Interview, InterviewQuestion, InterviewNote, InterviewSummary } from '@/types';

const feQuestions: InterviewQuestion[] = [
  {
    id: 'q-fe-001',
    text: 'Walk me through how you would architect a large React application. What patterns and tools would you use for state management, code splitting, and performance?',
    category: 'technical',
    requirementId: 'req-fe-1',
    requirementLabel: 'React',
    whyAsk: 'To assess depth of React architectural knowledge beyond component-level usage.',
    evidenceContext: 'Candidate has worked on large-scale React applications. This question validates breadth of understanding.',
    expectedEvidence: 'Clear articulation of state management strategy, understanding of rendering behavior, code splitting strategy.',
    addedToInterview: true,
  },
  {
    id: 'q-fe-002',
    text: 'Describe a TypeScript challenge you encountered in production and how you resolved it.',
    category: 'technical',
    requirementId: 'req-fe-2',
    requirementLabel: 'TypeScript',
    whyAsk: 'To validate that TypeScript usage is real and deep, not superficial.',
    evidenceContext: 'Candidate describes TypeScript on resume. Need production-level evidence.',
    expectedEvidence: 'A real type challenge — generics, conditional types, module boundaries, strict null checks.',
    addedToInterview: true,
  },
  {
    id: 'q-fe-003',
    text: 'Tell me about a frontend performance problem you diagnosed and fixed. What metrics did you use to measure it?',
    category: 'technical',
    requirementId: 'req-fe-6',
    requirementLabel: 'Performance optimization',
    whyAsk: 'Performance optimization is a preferred requirement. Candidate claims LCP improvement in resume.',
    evidenceContext: 'Resume mentions 30% LCP improvement from CRA→Next.js migration.',
    expectedEvidence: 'Specific metrics (LCP, CLS, FID), profiling tools, concrete before/after results.',
    addedToInterview: true,
  },
  {
    id: 'q-fe-004',
    text: 'You mentioned migrating to Next.js. Can you describe the migration approach, the specific challenges you encountered, and how you validated the improvement?',
    category: 'validation',
    requirementId: 'req-fe-5',
    requirementLabel: 'Next.js',
    whyAsk: 'Next.js is a preferred requirement. Candidate mentions the migration but depth needs validation.',
    evidenceContext: 'Resume: "Migrated merchant dashboard from CRA to Next.js." Interview should establish whether candidate drove or participated.',
    expectedEvidence: 'Concrete migration strategy, routing changes, ISR/SSR decisions, deployment approach.',
    addedToInterview: true,
  },
  {
    id: 'q-fe-005',
    text: 'Describe your experience leading a frontend team or mentoring engineers. How did you balance individual work with leadership responsibilities?',
    category: 'experience',
    requirementId: 'req-fe-8',
    requirementLabel: 'Team/tech leadership',
    whyAsk: 'Leadership experience is partial in the resume. Need to understand scope and approach.',
    evidenceContext: 'Resume describes a 4-person team but lacks detail on leadership style or outcomes.',
    expectedEvidence: 'Specific examples of technical decisions, mentoring outcomes, conflict resolution, process improvements.',
    addedToInterview: true,
  },
  {
    id: 'q-fe-006',
    text: 'How did you design the component architecture for your design system? What decisions did you make around API surface, versioning, and adoption?',
    category: 'project',
    requirementId: 'req-fe-7',
    requirementLabel: 'Design system contributions',
    whyAsk: 'Candidate built a design system. This validates depth of ownership and architectural thinking.',
    evidenceContext: 'Resume: "Built Zenpay Design System (Figma + Storybook + npm package)"',
    expectedEvidence: 'Component API design philosophy, token structure, versioning strategy, team adoption approach.',
    addedToInterview: false,
  },
];

const interviewNotesAarav: InterviewNote[] = [
  {
    id: 'note-001',
    questionId: 'q-fe-001',
    questionText: 'React architecture question',
    content: 'Candidate described React Context + Zustand for state management, React.lazy for code splitting, and mentioned using the profiler to identify unnecessary renders. Gave clear examples from Zenpay.',
    requirementId: 'req-fe-1',
    requirementLabel: 'React',
    flaggedForFollowUp: false,
    timestamp: '2026-09-15T10:15:00Z',
    type: 'evidence',
  },
  {
    id: 'note-002',
    questionId: 'q-fe-002',
    questionText: 'TypeScript challenge',
    content: 'Described creating a type-safe API client using generics and discriminated unions. Mentioned migrating legacy PropTypes to TypeScript interfaces across 40+ components. Very detailed.',
    requirementId: 'req-fe-2',
    requirementLabel: 'TypeScript',
    flaggedForFollowUp: false,
    timestamp: '2026-09-15T10:28:00Z',
    type: 'evidence',
  },
  {
    id: 'note-003',
    questionId: 'q-fe-003',
    questionText: 'Performance question',
    content: 'Walked through LCP investigation using Chrome DevTools and Lighthouse. Identified hero image not preloaded, blocking scripts. Implemented image optimization and script deferral. Showed 30% LCP reduction from 3.2s to 2.1s.',
    requirementId: 'req-fe-6',
    requirementLabel: 'Performance optimization',
    flaggedForFollowUp: false,
    timestamp: '2026-09-15T10:42:00Z',
    type: 'evidence',
  },
  {
    id: 'note-004',
    questionId: 'q-fe-004',
    questionText: 'Next.js migration',
    content: 'Candidate said they migrated the app from CRA to Next.js. Described using ISR for product pages, static export for marketing pages. Mentioned challenges with webpack config differences.',
    requirementId: 'req-fe-5',
    requirementLabel: 'Next.js',
    flaggedForFollowUp: true,
    timestamp: '2026-09-15T10:55:00Z',
    type: 'note',
  },
  {
    id: 'note-005',
    questionId: 'q-fe-005',
    questionText: 'Leadership question',
    content: 'Manages 4 engineers. Described weekly 1:1s, PR review rotation, and architecture RFC process. Mentioned helping a junior go from 0 to shipping independently in 3 months. Strong mentoring focus.',
    requirementId: 'req-fe-8',
    requirementLabel: 'Team leadership',
    flaggedForFollowUp: false,
    timestamp: '2026-09-15T11:08:00Z',
    type: 'evidence',
  },
];

const interviewSummaryAarav: InterviewSummary = {
  keyEvidence: [
    'Strong React architecture understanding with production examples.',
    'Deep TypeScript usage — generics, discriminated unions, large codebase migration.',
    'Concrete performance optimization with measured LCP improvement (3.2s → 2.1s).',
    'Next.js migration experience — validated ISR, static export, webpack differences.',
    'Team leadership with mentoring track record.',
  ],
  requirementCoverage: [
    { requirementId: 'req-fe-1', label: 'React', status: 'covered' },
    { requirementId: 'req-fe-2', label: 'TypeScript', status: 'covered' },
    { requirementId: 'req-fe-3', label: '3+ years experience', status: 'covered' },
    { requirementId: 'req-fe-4', label: 'CSS / design systems', status: 'covered' },
    { requirementId: 'req-fe-5', label: 'Next.js', status: 'covered' },
    { requirementId: 'req-fe-6', label: 'Performance optimization', status: 'covered' },
    { requirementId: 'req-fe-7', label: 'Design system contributions', status: 'covered' },
    { requirementId: 'req-fe-8', label: 'Team/tech leadership', status: 'partial' },
  ],
  strongEvidence: [
    'React architecture and production scale.',
    'TypeScript depth — generics and large codebase migration.',
    'Performance metrics-based optimization.',
    'Design system ownership with adoption evidence.',
  ],
  unresolvedQuestions: [
    'Leadership scope: tech lead or also people manager? No direct reports confirmed.',
  ],
  contradictions: [],
  followUpNeeded: [
    'Confirm whether Next.js migration challenges included edge runtime differences or just webpack.',
    'Clarify leadership — did candidate have formal performance review responsibility?',
  ],
};

export const mockInterviews: Interview[] = [
  {
    id: 'int-001',
    candidateId: 'cand-001',
    jobId: 'job-fe-001',
    status: 'completed',
    scheduledAt: '2026-09-15T10:00:00Z',
    completedAt: '2026-09-15T11:30:00Z',
    interviewers: ['Alex Rivera', 'Jordan Kim'],
    questions: feQuestions,
    notes: interviewNotesAarav,
    summary: interviewSummaryAarav,
  },
  {
    id: 'int-002',
    candidateId: 'cand-002',
    jobId: 'job-fe-001',
    status: 'completed',
    scheduledAt: '2026-09-16T14:00:00Z',
    completedAt: '2026-09-16T15:30:00Z',
    interviewers: ['Alex Rivera'],
    questions: feQuestions.slice(0, 4),
    notes: [
      {
        id: 'note-006',
        questionId: 'q-fe-001',
        questionText: 'React architecture',
        content: 'Described Redux Toolkit + RTK Query for state and data fetching. Clear understanding of React rendering model. Mentioned Shopify Polaris constraints.',
        requirementId: 'req-fe-1',
        requirementLabel: 'React',
        flaggedForFollowUp: false,
        timestamp: '2026-09-16T14:12:00Z',
        type: 'evidence',
      },
      {
        id: 'note-007',
        questionId: 'q-fe-003',
        questionText: 'Performance question',
        content: 'Reduced bundle by 40% via code splitting. Used webpack-bundle-analyzer. Good understanding but performance was more build-time than runtime UX.',
        requirementId: 'req-fe-6',
        requirementLabel: 'Performance',
        flaggedForFollowUp: true,
        timestamp: '2026-09-16T14:35:00Z',
        type: 'note',
      },
    ],
    summary: {
      keyEvidence: [
        'Strong React with Redux Toolkit.',
        'Good bundle optimization skills.',
        'TypeScript at Shopify scale.',
      ],
      requirementCoverage: [
        { requirementId: 'req-fe-1', label: 'React', status: 'covered' },
        { requirementId: 'req-fe-2', label: 'TypeScript', status: 'covered' },
        { requirementId: 'req-fe-3', label: '3+ years experience', status: 'covered' },
        { requirementId: 'req-fe-5', label: 'Next.js', status: 'partial' },
        { requirementId: 'req-fe-6', label: 'Performance optimization', status: 'partial' },
        { requirementId: 'req-fe-8', label: 'Team leadership', status: 'not_covered' },
      ],
      strongEvidence: ['React and TypeScript depth.', 'Bundle optimization.'],
      unresolvedQuestions: ['Leadership scope not discussed. Next.js depth unclear.'],
      contradictions: [],
      followUpNeeded: ['Follow up on runtime performance (not just build-time).', 'Ask about leadership aspirations.'],
    },
  },
  {
    id: 'int-003',
    candidateId: 'cand-005',
    jobId: 'job-fe-001',
    status: 'scheduled',
    scheduledAt: '2026-09-20T11:00:00Z',
    interviewers: ['Jordan Kim'],
    questions: feQuestions.slice(0, 3),
    notes: [],
  },
];

export const getInterviewsForCandidate = (candidateId: string): Interview[] =>
  mockInterviews.filter(i => i.candidateId === candidateId);

export const getInterviewById = (id: string): Interview | undefined =>
  mockInterviews.find(i => i.id === id);
